### ISSUE TITLE
Consider Websockets for updating stations

### ISSUE THREAD

**Issue by Empty2k12** [NeoLegends/velocity-pwa#29]
Polling every minute is very inefficient and slow. 

Consider using one of the available Websocket data sources for transparent updates in near-realtime.

**Comment by NeoLegends** [comment]
PRs welcome 😄

**Comment by NeoLegends** [comment]
Alternatively we can consider changing the poll interval to 20s.

**Comment by Empty2k12** [comment]
> Alternatively we can consider changing the poll interval to 20s.

Don't do it

**Comment by NeoLegends** [comment]
Wenn ihr SSE einbaut mache ich das vllt wirklich.

**Comment by Empty2k12** [comment]
Can you access SSE on a domain that your frontend is not hosted on?

**Comment by NeoLegends** [comment]
Not sure, but proper CORS headers will resolve that.

**Comment by NeoLegends** [comment]
Not sure though about adding a dependency to your servers. How's your uptime been?

**Comment by Empty2k12** [comment]
`Access-Control-Allow-Origin: *`will be regeling!

**Comment by NeoLegends** [comment]
This will actually require a large(ish) refactor of the hooks code, because currently it's all based on wrapping the official REST API and polling periodically.

**Comment by Empty2k12** [comment]
That's why we're using Redux for state management and time-traveling debugging. But I can see why you chose a different solution based on your requirements. Not sure how to best adapt/combine both..

**Comment by NeoLegends** [comment]
Well, at least the data fetching would need to be changed. This would be possible and the hook surface wouldn't need to change much (if at all). Redux wouldn't really provide an advantage here.
