### ISSUE TITLE
Reloading causes slight shift in map

### ISSUE THREAD

**Issue by Empty2k12** [NeoLegends/velocity-pwa#30]
Reloading the page causes a slight shift when the map position is loaded from localStorage.

Research solutions that prevent this from happening.

**Comment by Empty2k12** [comment]
![Bug in Action!](https://media.giphy.com/media/lOUztj4pegwm9UcD7o/giphy.gif)

**Comment by NeoLegends** [comment]
Yeah this is something with leaflet-react. I just tried using `useLayoutEffect` for loading the cached viewport, but that didn't change anything. So I figure I'll just leave it as it is right now. If you want to take a look at it, PRs welcome.

**Comment by Empty2k12** [comment]
Why close it then? Mark as bug and good-first-issue and you're golden.
