### ISSUE TITLE
Toasts do not hide when they've been suspended for some time.

### ISSUE THREAD

**Issue by Empty2k12** [NeoLegends/velocity-pwa#31]
If you rent a bike and then lock your screen, upon unlocking minutes later, the toasts will attempt to display for their designated time. Instead, they should have a time until they're allowed to show and instantly hide if that time passed.

**Comment by LucasForster** [comment]
See #22.

**Comment by Empty2k12** [comment]
This should be closed and #22 reopened. This is why you don't close valid issues just because there's no feasible solution for them now.
