### ISSUE TITLE
Display date string in correct locale

### ISSUE THREAD

**Issue by sudmann** [NeoLegends/velocity-pwa#43]
Currently, all the date strings in the "bookings" tab are formatted in english, no matter the chosen language. This should be fixed to stay consistent with the language.
![Screenshot_20200109_004835](https://user-images.githubusercontent.com/29508830/72026052-75aea480-327a-11ea-90bf-cc0984c599a2.png)

**Comment by NeoLegends** [comment]
This is AFAIT an issue with your browser, but I‘ll merge the associated PR anyway to fix that once and for all. 

My phone, for example:
![672BB95A-3732-4605-854B-DD05D0A63B58](https://user-images.githubusercontent.com/1683034/72053681-cc8e9b00-32c7-11ea-806a-60c51d619984.png)

**Comment by sudmann** [comment]
> all the date strings in the "bookings" tab are formatted in english

should have been "are formatted in the browser's locale". On my phone everything was also in German.
If you'd switched to English you would have seen the issue.
