### ISSUE TITLE
Refactor popup logic

### ISSUE THREAD

**Issue by NeoLegends** [NeoLegends/velocity-pwa#5]
Booking & renting logic is currently split between the bike-map and rent-popup components. This creates some complications in regards to clear separation of concerns. We should move the booking & renting logic into rent-popup entirely.

**Comment by LucasForster** [comment]
Basically, you would remove the "Active reservation" field from the "Bookings"-tab.

It contains the following information which needs to be integrated into the rent-popup:
- Station name
  This is basically covered by the rent-popup: When open, you either see a station name in the "Cancel booking"-button, or nothing, which means that the booking is for this particular station.

  However, this might be a bit unclear when you're actually not remembering which station you booked. The information should be integrated into the map (without opening a station) e.g. **by changing the station icon** to, let's say, [a gear wheel containing an 'R' for "reservation"](https://upload.wikimedia.org/wikipedia/commons/d/d5/Rust_programming_language_black_logo.svg).

- The reserved slot's number
  This is **already fully integrated** into the rent-popup: When selecting or booking a bike, the slot gets pre-selected (and you can choose another bike if you want to).

- The time until the booking is valid
  This could be integrated directly into the rent-popup as an **information below the cancellation button** (something like "auto-cancelling in ..."). With more effort, the "reserved logo" described above could carry this information in its color (changing from green to red when the time runs out).

**Comment by NeoLegends** [comment]
> Basically, you would remove the "Active reservation" field from the "Bookings"-tab.

Nah, this ticket is solely related to the code base, not to anything user-related.

**Comment by NeoLegends** [comment]
I'm open to making the rent popup take over the responsibilities of the bookings tab in regards to the currently active booking, but let's create a separate issue for that.
