### ISSUE TITLE
Booking is broken

### ISSUE THREAD

**Issue by Empty2k12** [NeoLegends/velocity-pwa#51]
It seems there was a regression introduced in #48 which renders Velocity.ac unable to rent bikes.

Sadly, there's no more information available about this issue as it only happens when you're at a station actually trying to rent a bike which mostly happens on mobile devices with limited debugging tooling available.

**Comment by NeoLegends** [comment]
Velo re-enters bikes that haven't been taken out of the station into the system after 30s. So you could, for example, try renting a bike from home at a remote station and debug on that.

**Comment by Empty2k12** [comment]
> Velo re-enters bikes that haven't been taken out of the station into the system after 30s. So you could, for example, try renting a bike from home at a remote station and debug on that.

Sadly, this behaviour changed since the smart-locks have been introduced: The renting procedure will first unlock the smart-lock, if that was successful release the bike from the station. Thus, if you rent, the smart-lock will open and since you cannot remotely close it stay open and the bike will display as `reserved` at the station until someone closes the smart lock.

**Comment by NeoLegends** [comment]
Oh gosh. Perhaps we'll have to do some field-work in the next week.

**Comment by Empty2k12** [comment]
This has been resolved in #52
